

spring:
#  datasource与hikaricp的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://120.78.205.51:3306/mysite?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: rootroot
  application:
    name: xiaobingserver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zpy.xiaobingmybatis.entity


#showSql
#logging:
#  level:
#    com:
#      zpy:
#        xiaobingmybatis:
#          mapper : debug

  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 7070